<?php

namespace App\Models;

use App\Models\Traits\Taggables;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Resource extends Model
{
    use HasFactory,Taggables;

    protected $fillable = ['name'];

    public function newFromBuilder($attributes = [], $connection = null)
    {
        if (isset($attributes->type) && $attributes->type == 2) {
            unset($attributes->type);
            $model = (new Post)->newInstance([],true);

            $model->setRawAttributes((array) $attributes, true);

            $model->setConnection($connection ?: $this->getConnectionName());

            $model->fireModelEvent('retrieved', false);
            return $model;
        }
        return parent::newFromBuilder($attributes, $connection); // TODO: Change the autogenerated stub
    }

}
